volumina/layer.py
Previously, the method `_updateNumberOfChannels` was not call in the constructor of `Layer`. This has since been addressed. As a consequence, `_updateNumberOfChannels` has been restructured to handle various cases including having no layers specified, having multiple `None` layers specified, etc. This should make instances of `Layer` more robust at handling changes in the number of channels.
This has been broken out of the original pull request ( https://github.com/ilastik/volumina/pull/152 ).
=> Fixes for volumina/layer.py regarding updating number of channels at initialization

tests/imagesources_test.py, volumina/layer.py, volumina/pixelpipeline/imagesources.py
Provides support for masked arrays in volumina. In most cases, this is a series of minor fixes to volumina to ensure support of masked arrays. In a few cases, more heavy duty code is required to bring about support. Most of the support is already available to thanks to ( https://github.com/hmeine/qimage2ndarray ). Masked arrays appear basically the same NumPy ndarrays except that they mask results. In an image source, the masked regions are made transparent. This is related to several issues ( https://github.com/ilastik/ilastik/issues/1076 ) (  https://github.com/ilastik/lazyflow/issues/162 ) ( https://github.com/ilastik/volumina/issues/151 ).
=> Masked arrays i.e. Handle frames of variable size (with known maximum)

volumina/imageScene2D.py, volumina/tiling.py, volumina/volumeEditorWidget.py
When loading videos with high resolution (eg: 3072x3072 larvae videos), the default current tiling block size of 256 creates a lot of tiles and therefore scrolling from frame to frame becomes really slow. We are now choosing the block size based on slice shape (only if it exceeds the default value 256). I tested this of 2D and 3D data sets.
@stuarteberg I think the code is safe, but could you review it just in case?
=> Setting tiling block size based on slice shape

volumina/eventswitch.py, volumina/sliceSelectorHud.py
Previously, all mouse events not originating from viewports were filtered out. With the changes introduced by this PR, events from the parent of the respective viewport, which is ```ImageView2D``` are also accepted. (The HUD events are propagated to those ```ImageView2D``` as well).
I didn't do a terrible amount of testing, but it seems to work.
=> Enables drawing within the (transparent) HUD area at the top of the viewports

volumina/interpreter.py, volumina/navigationController.py
Set click events to accepted when they are handled, because otherwise the right-click context
menu of object classification and tracking showed up twice.
I verified that this works for ObjectClassification and Tracking with ObjectClassification on Mac.
And it still accepts clicks between the HUD buttons.
=> Do not handle mouse click events twice

tests/datasourcefactories_tests.py, volumina/_testing/from_lazyflow.py, volumina/pixelpipeline/_testing.py
Declaring operator slots with a list is deprecated, see https://github.com/ilastik/lazyflow/pull/250
* replaced all list style slot declarations with _fancy syntax_
=> refactor: declare each slot explicitly

volumina/navigationController.py
we need _default for left click also
and because there is nothing specific to the RightClick in onMousePressRight_default
we can use it for all mouse clicks
that are not handled with higher priority in the if statement
type of the mouse click is passed via event parameter
=> mouse single left click taken as a double click

volumina/pixelpipeline/datasources.py, volumina/widgets/dataExportOptionsDlg.py, volumina/widgets/slotMetaInfoDisplayWidget.py
volumina assumes axis order 'txyzc', which is no longer the lazyflow default
=> Feature user axis order

circle.yml
Seems like the conda guys have restructured the folders a bit.
=> Quickfix: CircleCI build: point to correct activate script

volumina/utility/shortcutManager.py
comparing very similar ActionInfo objects lead to error due to incomparability of functions => ignore functions (and widgets...)
=> restrict comparison of ActionInfo objects

volumina/widgets/slotMetaInfoDisplayWidget.py
This is the second PR in the quest to fix the label-import (currently it's broken).
Needs: https://github.com/ilastik/lazyflow/pull/280
Just makes sure that the `SlotMetaInfoWidget` works, even if there has not been any `OpReorderAxes` in the chain, which is the case when importing labels.
=> safely retrieve original shape

.pre-commit-config.yaml, .travis.yml, pyproject.toml, volumina/widgets/exportHelper.py, volumina/widgets/layercontextmenu.py
Motivation: I wanted to export some layer from the layerstack programmatically
in an ilastik gui test and not duplicate the whole functionality from volumina.
As it was implemented in volumina it was not possible to re-use the code in a
non-interactive way.
* I factored out some functions, hoping the code would be easier to read, and also in order to expose the `get_export_operator(layer)` function.
*  rename: `get_settings_and_export_layer` -> `prompt_export_settings_and_export_layer`
* Also properly configured black via `pyproject.toml` ([as they recommend in their docs](https://github.com/python/black#version-control-integration))
=> Refactor export helper

.circleci/config.yml, .travis.yml, tests/glview_test.py, volumina/config.py, volumina/view3d/glview.py
ilastik carving gui tests on Windows CI (appveyor) failed because
the 3D widget would raise an error when drawing 3D stuff, as the
provided GL version (1.0, 1.1) is not enough.
* Added a check to GLView, to get the current OpenGL version
* Added a MockGLView that is replaced in Overview3D in case version
is not sufficient
* Config/environment variables:
* Config values can now be overriden via environment variables
* `VOLUMINA_VERBOSE_PIXELPIPELINE=1`, `VOLUMINA_SHOW_3D_WIDGET=0`
Related to  https://github.com/ilastik/ilastik/issues/1297 https://github.com/ilastik/ilastik/issues/1885
Todo:
=> added MockGLView to replace GLView if OpenGL < 2.0

volumina/__init__.py, volumina/api.py, volumina/viewer.py
this was only useful when we had the vtk widget, since this is gone now,
`NO3D` is not used anymore.
=> Removed NO3D flag

tests/glview_test.py, volumina/config.py, volumina/view3d/glview.py
Related to #239 #240 
there was a bug where `volumina.config.Config` was directly called
and not instantiated. Apparently the `Config.show_3d_widget` always
returns a property-object that is always interpreted as `True`.
* Use proper `volumina.config.CONFIG` object (uppercase).
* Hide `_Config` class.
=> fix properly use config to configure 3D view

volumina/navigationController.py
Mouse move events were delivered 2 times, and the second event was
delivered *after the next mouse move event*. For example, when dragging
the mouse to the right:
mouseMoveEvent: x=1 y=42  # Event #1, first delivery
mouseMoveEvent: x=3 y=42  # Event #2, first delivery
mouseMoveEvent: x=1 y=42  # Event #1, second (duplicate) delivery
...
This behavior produced non-empty boxes even when clicking on the canvas
without dragging.
Related to https://github.com/ilastik/ilastik/pull/2066.
=> Fix duplicate mouse move events

volumina/tiling.py
those messages were previously swallowed by `sys.excepthook` for some reason.
When these were changed to `logger.error` they were actually displayed.
https://github.com/ilastik/volumina/commit/2b09109b478a7f30787d9cecbad01ce82812a671
We want to restore the original behavior of hiding these. Hence, a lower log-
level should be used.
=> Reduce tiling logs from errors to debugs

volumina/widgets/layerwidget.py
For some reason, `LayerDelegate.handleRemovedRows` could be called when
the model's data does not contain an item for the `EditRole`.
Also, `QAbstractItemModel.rowsAboutToBeRemoved` signal has an inclusive
right boundary, so parameters have been renamed to `first` and `last`,
which is consistent with the [Qt documentation](https://doc.qt.io/qt-5/qabstractitemmodel.html#rowsAboutToBeRemoved).
Closes https://github.com/ilastik/ilastik/issues/1997.
=> Do not remove missing layers in LayerDelegate

volumina/brushingcontroller.py, volumina/eventswitch.py, volumina/interpreter.py, volumina/navigationController.py, volumina/skeletons/skeletonInterpreter.py, volumina/sliceSelectorHud.py, volumina/thresholdingcontroller.py, volumina/volumeEditor.py
Previously, EventSwtich installed itself as an event filter to both
ImageView2D (which is QGraphicsView) and it's viewport because a single
event filter should be able to catch all events (see https://stackoverflow.com/questions/2445997/qgraphicsview-and-eventfilter
for details). This made it hard to understand how events interact with
different event filters.
Another solution described in one of the anwsers in the link above is to
remove focus proxy from QGraphicsView. QAbstractScrollArea (superclass
of QGraphicsView) installs itself as a focus proxy to it's viewport
in order to be able to handle scrolling via keyboard. Since our
application doesn't need that, it is safe to remove the focus proxy and
simplify event handling.
However, HUD is currently displayed as a sibling of …
=> Move special case for mouse events to HUD

volumina/widgets/layercontextmenu.py
Edges are not stored as datasets and cannot be exported. This closes ilastik/ilastik#1895
=> disable export for edge layers

volumina/navigationController.py, volumina/view3d/overview3d.py, volumina/view3d/volumeRendering.py, volumina/volumeEditor.py
Since Python 3.7.4 an error bubbles up that has been ignored in previous Python versions.
The cause is `PyQt5` accessing all class attributes via `PyObject_GetAttr` during initialization of the Gui Widget. In our case, the class is not fully initalized by that time but class properties are still executed (via `PyObject_GetAttr`).
There are a couple of solutions to this problem ([related thread on riverbank mailinglist](https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042020.html)
* this PR: properties removed in favor of get/set functions.
* wait until PyQt5 5.13.1 is available on conda-forge -> the issue is fixed there
* switch to PySide2 for the whole of ilastik. Those are the official Qt bindings.
=> fixes crash related to Overview3d with Python 3.7.4 on OSX

tests/colortable_contextmenu_manual.py, tests/direct_layer_manual.py, tests/skeletons.py
volumina analogon to https://github.com/ilastik/ilastik/pull/2216
accessing the `.value` member on h5py groups is deprecated.
Gets rid of
```
H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
```
=> mnt: h5py deprecation of dataset.value -> dataset[()]

volumina/view3d/meshgenerator.py
Due to a bug (https://github.com/ilastik/marching_cubes/pull/23) in the marching cubes repo, smoothing rounds were off by one.
In order to retain consistent behavior we have to reduce the number of smoothing rounds.
(thanks to @stuarteberg for fixing it!)
=> Reduce number of smoothing rounds

volumina/widgets/slotMetaInfoDisplayWidget.py
Exception would occur on second instantiation of ExportOptionsDlg. Reason is
that it uses slotMetaInfoDisplayWidget that had properties.
See also https://github.com/ilastik/ilastik/pull/2276/commits
=> Fix error related to PyQT upgrade that didn't pop up so far

tests/test_utility/test_preferences.py, volumina/utility/preferences.py
this is _not_ the proper way to do it, we should still import all
preference properly (key bindings) https://github.com/ilastik/ilastik/issues/2323, and ignore deprecated ones https://github.com/ilastik/ilastik/issues/2322 that
also result in failures.
We need to fix this quickly for the release
This should of course be followed up properly.
This PR preserves the old file if import failed with the hope we'll properly fix it at some point.
=> temporary fix: fail a little more gracefully on pref import fail

tests/test_utility/test_preferences.py, volumina/utility/preferences.py, volumina/utility/shortcutManager.py
Old pickled preferences saved shortcuts as a dict with tuple keys, but
JSON can only have string keys, so transform the old dict into the new
format.
Closes https://github.com/ilastik/ilastik/issues/2323
=> Save shortcuts as list of dicts

volumina/imageScene2D.py, volumina/volumeEditor.py, volumina/volumeEditorWidget.py
I cannot believe that we did not have an issue about this open @akreshuk, but I couldn't find one.
With this PR we add a new preference key `"tileWidth3D"` which will be used to set tile width for 3D data. The preference key `"tileWidth"` remains and will be used for 2D data. Defaults are 256 for 3D, 512 for 2D.
I also moved responsibility for the preference handling from `ImageScene2D` to `VolumeEditorWidget`.
Added the setFocus so this PR actually closes an issue ;)
fixes ilastik/ilastik#2260
=> Set tilewidth automatically for 2D and 3D data

volumina/volumeEditorWidget.py
fixes https://github.com/ilastik/ilastik/issues/2422
looks like there was some copy-paste issue
Maybe interesting to add, that having a second shortcut on the same action seems to silently disable the action - no errors whatsoever...
=> fix short cut action slice up

.github/workflows/lint.yml, .github/workflows/test.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, Readme.md, conda-recipe/meta.yaml
Unrelated:
* Pinned lemon such that it is for sure a shared lib version. For some reason the solver might pick one of the old builds. Pinning it will not cause any problems - lemon doesn't really have upstream deps.
=> reflect default branch rename to main

volumina/utility/segmentationEdgesItem.py
see https://github.com/ilastik/ilastik/issues/2476
the finding of overlapping/colliding edges is too slow
CC: @stuarteberg
=> disable z-updates for overlapping edges for now

volumina/navigationController.py
Fix issue ilastik/ilastik#2009
Qt.AltModifier inverts vertical and horizontal scrolling directions as an [intended behaviour](https://bugreports.qt.io/browse/QTBUG-30948?focusedCommentId=202503&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-202503)
The change in indentation in line 36 was caused by `hook id: black` while committing.
Thus, I refrained from reverting it this time, but appreciate tips how to avoid such changes in the first place in the future.
=> Fix Scrolling: Alt + mouse wheel

volumina/layerstack.py
Added function to move a specific layer either to top of the layerstack (if it is at the bottom) or to the bottom (if anywhere else) So far only used for callbacks in layer shortcuts in ilastik (shortcut "i").
Co-Authored-By: Emil Melnikov <emilmelnikov@users.noreply.github.com>
=> Add toggleTopToBottom utility function

.gitignore, .pre-commit-config.yaml
`pre-commit` complains when using a repo with branch name as a ref.
Also, add `*.egg-info` directory from `pip install -e` to `.gitignore`.
=> Pin black version

.github/workflows/deploy.yml, .github/workflows/etc/ilastik-env.yaml, .github/workflows/lint.yml, .github/workflows/test.yml, volumina/colortables.py, volumina/layer.py, volumina/sliceSelectorHud.py, volumina/widgets/layerwidget.py
xref: https://github.com/ilastik/ilastik/pull/2740
=> reduce number of deprecation warnings

volumina/pixelpipeline/datasources/lazyflowsource.py, volumina/tiling/__init__.py
excepthook was used before in #251  2b09109b478a7f30787d9cecbad01ce82812a671 that claims segfaults being cause by it.
Could not reproduce segfaults - and rather have an error message popping up.
Otherwise in case of exception somewhere along the chain, ilastik looks like it's doing nothing and one wouldn't know.
=> stop hiding exceptions

volumina/colortables.py
When the constants are imported, any modifications to them persist until Python is restarted. Consumers currently have to make their own copy of the constant, which they shouldn't have to.
See https://github.com/ilastik/ilastik/pull/2786
=> Colortables: Provide unique copies of constants

.github/workflows/etc/ilastik-env.yaml
This changes nothing that could make the pipeline fail.
=> Disallow bad pyqt5-sip versions

tests/valueRangeWidget_test.py, volumina/widgets/dataExportOptionsDlg.py, volumina/widgets/valueRangeWidget.py
related to https://github.com/ilastik/ilastik/pull/2898
Comes down to remove explicit background color settings, or make them palette-dependent colors.
Also removed unnecessary validation code in `ValueRangeWidget` (added some more tests instead ;))
=> Fixes for dark mode display

tests/test_pixelpipeline/test_datasources/test_cachesource.py, tests/test_pixelpipeline/test_datasources/test_factories.py, volumina/pixelpipeline/datasources/cachesource.py, volumina/pixelpipeline/datasources/factories.py, volumina/pixelpipeline/imagepump.py
Volumina caches requests since #255. Unfortunately this also caches requests that fail, and once a lazyflow request fails, it is permanently failed.
By dropping failed requests, failed tiles can be retried in 3D datasets - by scrolling away and back to the same view. Retrying in 2D will take more work, but also depends on this fix.
This is probably easier than reworking requests to be re-usable...
Edit/Clarification: I realised that for now this only leads to "retries" for volumina tiles whose underlying data can partially fail 😅 specifically, tiles that depend on multiple OME-Zarr chunks.
=> Stop caching failed requests

volumina/tiling/cache.py
fixmes are not user warnings. This message appears for every user on win and linux (not to mention our test logs), and it's pointless for them.
=> Silence tilescache warning
