ilastik/volumina

volumina/brushingcontroller.py
volumina/navigationController.py
volumina/thresholdingcontroller.py

Changed all occurrences of "controler" to "controller".

Corrected spellings

---

volumina/widgets/layercontextmenu.py

A small change.  I put the menu addAction for export into the body of the code that actually creates the export item.

Fixed issue with adding None menu item;

---

volumina/sliceSelectorHud.py

time slider buttons changed/added and time spin box size changed

---

tests/colortable_contextmenu_manual.py
tests/tiling_tests.py
volumina/brushingmodel.py
volumina/imageView2D.py
volumina/navigationController.py
volumina/patchAccessor.py
volumina/quadsplitter.py
volumina/skeletons/skeletonsLayer.py
volumina/testing.py
volumina/volumeEditorWidget.py
volumina/widgets/wysiwygExportOptionsDlg.py

**Tag**: py2to3_v0.2
**Details**: PEP238 support for integer division using future import division.
**Test status**:
- Most of the changes tested - list attached ([v1.2_Overall_result.xlsx](https://github.com/ilastik/volumina/files/461749/v1.2_Overall_result.xlsx))
- unit tests  
- manual invocation of application; and/or 
- python -3 switch
- Some changes could not be reached and are asserted <br \>
- Testing of Automatic tracking is pending and shall be taken up later along with HyTra framework - see comment from @chaubold (https://github.com/ilastik/ilastik/pull/1329)

Py2to3 volumina

---

volumina/croppingMarkers.py

needed in learning for training applet where editability must be turned off

adds editability on/off for crop lines

---

volumina/croppingMarkers.py
volumina/interpreter.py

needed in hytra-learning #1377

toolTip signal added to ClickReportingInterpreter

---

volumina/quadsplitter.py
volumina/volumeEditor.py

ensures proper shape change when, for example, changing from txy to zxy axes

always update shape in volume editor

---

circle.yml

To make the tests run again...

Update Circle CI configuration to new Python 3 setup

---

volumina/sliceSelectorHud.py

merging this into master should be done when pgmlink is no longer needed on windows
(pgmlink needs crops and full annotations in each crop)
needed for 
https://github.com/ilastik/ilastik/pull/1531

removing crops

---

volumina/view3d/glview.py

Added the potential to set the background color via the config, with white as default.

White color background in 3D widget

---

volumina/widgets/wysiwygExportOptionsDlg.py

which didn't work as noted in #195

Fix wysiwyg

---

volumina/view3d/glview.py
volumina/view3d/overview3d.py
volumina/view3d/ui/view3d.ui
volumina/volumeEditor.py

See https://github.com/ilastik/ilastik/issues/1666 for more details
Depends on https://github.com/ilastik/ilastik/pull/1686

Show 3D widget only when necessary

---

volumina/navigationController.py

scrolling lead to TypeError: 'tuple' object does not support item assignment

make sure to manipulate slicingPos or cursorPos as list (not tuple)

---

volumina/thresholdingcontroller.py

fixes #1294
Window leveling is now performed without limit checks. If they need to be done, it has to be done in a different way. 
Until now the allowed limits where hard coded to the max range of 12 Bits. There are images however, that come with a far higher range of level values. This feature was responsible for the issue #1294.
One mouse movement now changes either the window level (x-direction) or the window size (y-direction) and not both at the same time. Makes it handier.

enhancement issue#1294

---

volumina/colortables.py

Adds a new default 16-color colortable, needed by ilastik/ilastik#1723.

Fix colortable

---

CONTRIBUTING.md

Added contribution guidelines with reference to the main ones in the ilastik repository, just for completeness

added contributing guidelines with reference to ilastik ones

---

volumina/colorama/ansitowin32.py

I am not sure why colorama is embeded into our codebase, maybe it's better to migrate to upstream version in the future

Fix IO on closed stream (Windows)

---

volumina/layer.py
volumina/pixelpipeline/datasources.py

Questionable. I don't have enough understanding of dataflow on rendering.
If I don't reset bounds on channel change, then it will degrade to minmax value accross all channels.

[RFC] Re-normalize on channel change. Closes: ilastik/ilastik#1741

---

examples/streamingViewer.py
volumina/widgets/hdf5ExportFileOptionsWidget.py
volumina/widgets/multiformatSlotExportFileOptionsWidget.py
volumina/widgets/n5ExportFileOptionsWidget.py
volumina/widgets/n5ExportFileOptionsWidget.ui

This contributes to fixing ilastik/ilastik#1788

Import/Export N5 files

---

.editorconfig
.gitattributes

Spaces removed with following command
```bash
find ./ -iname "*.py" -type f -print0 | xargs -0 sed -i 's/[[:space:]]*$//' 
```

Add editor config

---

volumina/api.py
volumina/layer.py

should have sen this coming, but well, here we go now.
reference: https://github.com/ilastik/volumina/pull/228 https://github.com/ilastik/ilastik/pull/2012

expose createDataSource via api, fix bug

---

volumina/tiling.py

Don't call sys.excepthook as it causes qt to segfault use logging facilities instead

---

volumina/layer.py
volumina/widgets/layerDialog.py
volumina/widgets/thresholdingWidget.py

Simplifies NormalizableLayer, removing the nebulous concept of "range" in favor of only using the "normalize" values. Cleans up and removes a lot of replication from layerDialog.py
Companion ilastik PR: https://github.com/ilastik/ilastik/pull/2282
Fixes #https://github.com/ilastik/ilastik/issues/2281
Fixes https://github.com/ilastik/ilastik/issues/2195

Fix layer thresholds popup

---

volumina/view3d/glview.py

See https://bugreports.qt.io/browse/QTBUG-87014 for details.
Related: https://github.com/ilastik/ilastik/pull/2345

Add workaround for macOS Big Sur

---

volumina/utility/segmentationEdgesItem.py

Fixes ilastik/ilastik#2476
Split from https://github.com/ilastik/volumina/pull/286

Fix clickable area on higher zoom levels

---

conda-recipe/meta.yaml

i suspect that was a typo on my end :/

allow all newer versions of lemon

---

.github/workflows/etc/ilastik-env.yaml
.github/workflows/test.yml
conda-recipe/meta.yaml
tests/glview_test.py
volumina/widgets/dataExportOptionsDlg.py
volumina/widgets/dataExportOptionsDlg.ui
volumina/widgets/dvidVolumeExportOptionsWidget.py
volumina/widgets/singleFileExportOptionsWidget.py
volumina/widgets/stackExportFileOptionsWidget.py

Hello all,
This small PR aims adds a reset button to the export gui so a user can revert to default "magic" path more easily. The corresponding ilastik PR can be found https://github.com/ilastik/ilastik/pull/2620

Add button resetpath

---

.github/workflows/test.yml
conda-recipe/meta.yaml
tests/brushingmodel_test.py
tests/conftest.py
tests/imageScene2D_test.py
tests/layerwidget_test.py
tests/lazy_test.py
tests/tiling_test.py
volumina/pixelpipeline/datasources/factories.py
volumina/slicingtools.py

mostly test failures related to fringe usage QApplication - mostly resolved using qapp fixture.
Running on Big Sur and newer fixed for free by using python >3.7
fixes #295
fixes #289 
fixes #288

fixes for python 3.8, 3.9

---

.github/workflows/test.yml
volumina/config.py
volumina/imageView2D.py

Just tried this following our discussion whether `volumina` was using opengl during the meeting. Turns out this looks very promising - speedup in rendering is _very_ noticable. 
much faster rendering, especially in multicut with edge overlays.
enjoying some free lunch for now.
cc: @Tomaz-Vieira @emilmelnikov @btbest 
need to investigate some `QOpenGLFramebufferObject: Framebuffer incomplete attachment` "warnings" here and there...

enable QGL viewport

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml

* use Miniforge with libmamba solving
* use conda-build for builds

MNT: Update ci

---

Readme.md
volumina/viewer.py
volumina/viewer.ui

Fix linux not rendering
